apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
spec:
  serviceName: "backend-service"
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: my-backend-image
        imagePullPolicy: Never 
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: backend-storage
          mountPath: /data
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-pvc